### ISSUE TITLE
Google images not downloading anymore

### ISSUE THREAD

**Issue by twinters** [korymath/talk-generator#1]
The Google image search function doesn't download any new images anymore now that it checks local cache. It only looks for local images

This is probably due to the "search_google_images=False" in the header of "get_images", as this will by default falsify line 182 (if len(all_paths[word]) == 0 and search_google_images:).
I'm not sure whether search_google_images should be true, or the "and" should be an "or" in search_google_images, or whether this variable should be removed (as it might be a leftover from testing) as this all depends on the intended semantics of that variable.

Removing the variable from the conjunction seems to fix the problem, as it still downloads if the images wasn't downloaded before, and uses the cache otherwise.
Could you take a look at it to see what was intended?

**Comment by korymath** [comment]
Sure thing, sorry about the breaking change. Working on it now.

**Comment by korymath** [comment]
For reference, it is best to add run code to reproduce the error and any sort of error message (which there most likely is not for this issue).

I removed that variable, was just using it as a flag when I was on really bad wifi.
