### ISSUE TITLE
Parallellisation of slide generators

### ISSUE THREAD

**Issue by twinters** [korymath/talk-generator#10]
Currently, generating the powerpoint takes quite some time. This could be sped up by generating the slides in parallel. This does have some implications for the code structure, and some dependencies that have to be taken into account:

- `python-pptx` is not able to change the positions of slides, and slides have to be added incrementally. As such, instead of the `slide_templates` module generating the slide, it should return a function to add the slide, and the required slide generation arguments (=the generated content). The program can then add all of these one after another after all these objects are generated
- The slide creation methods have boolean conditions checking if certain required content is present, before generating. This should be extracted out, such that this can be checked beforehand. An alternative is replacing this system with another way of checking if the required content got generated (or possibly always providing an alternative backup option)
- There is a variable saying how much repeating elements between generated slides are allowed. This should still be respected, as it makes sure the slides feel original when they need to. The new interface for generating slides should thus also return a function that can be called in case the generated content is not satisfyin these originality constraints

**Comment by korymath** [comment]
These are great points, and a fantastic high level design choice. Do we want an eager mode and an offline mode... what I mean to say is: 

```
is there ever a moment when you might want the system to just make a next slide (like a generator), or do you always want to build a stack of slides
```

What is the slow part? I presume it is the latency on the web API calls? 
Is there a way of caching data from the request to be used on later slides to minimize calls?
Repeating elements is interesting, how do we measure that similarity?

**Comment by korymath** [comment]
Testing with the new parallel capabilities in the 'dev' branch. For instance, on my computer (MacBook Pro) I have the following results of stress_test.py

python run.py --parallel=True --num_slides=10 --topic=${TOPIC} --open_ppt=False
Made 10 talks with an average of 19.107896947860716 seconds, std: 8.000154629266456

python run.py --parallel=False --num_slides=10 --topic=${TOPIC} --open_ppt=False
Made 10 talks with an average of 48.68645820617676 seconds, std: 9.369923339508231

**Comment by korymath** [comment]
Closed with /dev branch merge. Nice work @TWinters
