### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by twinters** [korymath/talk-generator#11]
The codebase is too diffucult to easily be used by (often non-tech-savvy) improvisators. As such, we should probably provide a web interface for our system at this point. We will be able to hide required credentials (e.g. for reddit and wikihow) in the server variables. A good place to host it for free is [Heroku](https://heroku.com).

The web interface itself should probably just present a text box for the topic and a generate button, and possibly also the options to determine the number of slides and possibly the name of the presenter.

**Comment by korymath** [comment]
I am working through on this. 

Are you imagining that the slides will then be downloaded by the user, or that they would be presented in the browser? In my head the first step is to create the presentation on the server and then offer the file for download for the user and then they can present it on their system? Does that sound right?

**Comment by korymath** [comment]
Starting toward this: https://korymath-automated.herokuapp.com/

**Comment by korymath** [comment]
This is now closed thanks to the incredible work by @TWinters and @h0h0h0
