### ISSUE TITLE
Keeping the slide topic seeds simple

### ISSUE THREAD

**Issue by twinters** [korymath/talk-generator#12]
Currently, our system uses a generator that uses related conceptnet words to generate the next topic seed for a slide (where it comes back to the presentatation topic every couple of slides).
These seeds are sometimes uncommon words or not even words at all. They've also got different part of speeches often.
It might be interesting to look into n-grams to make the slide topic seed generator "prefer" more common words.
It might also be interesting to constrain the seeds to only be a noun, as that seems to work best with the current slide generators.
It might also be interesting to look at different graphs for generating related words, such as Wikipedia and Wiktionary links. The slide topic seed generator can then switch between these for more interesting and different types of results.

**Comment by korymath** [comment]
There is a wordnet that we can use to zoom up and down the hierarchy of words. Something like this: https://stackoverflow.com/questions/24217776/get-all-grandchildren-holonym-for-a-grandparent-hypernym-in-wordnet

So the minimum viable way that we might do it is to try to extract the sentence subject from the topic seed that is presented to the system, and then generate based on that simplified seed...

**Comment by korymath** [comment]
I think the best thing to do would be to use a single input word from the user and nothing more. 
We constrain ourselves, but this is an easy problem to solve. Just accept a single input word.
