### ISSUE TITLE
Setup as a Python Package so it can be installed and tested

### ISSUE THREAD

**Issue by h0h0h0** [korymath/talk-generator#21]
At some point, we can change the package structure so that it could be installed and tested using python tools. 

Making this a python package does _not_ mean it will be public or in Pypi. Making this a package will allow talk-generator libraries and generators to be imported and used by other python applications in a more versatile way.

**Comment by korymath** [comment]
@h0h0h0 what is the current state of affairs with packaging things up?

**Comment by korymath** [comment]
This is currently fixed in 
https://github.com/korymath/talk-generator/pull/36

Waiting on review and then will close this issue.
