### ISSUE TITLE
Click Here to Add Text in empty slide title boxes. 

### ISSUE THREAD

**Issue by h0h0h0** [korymath/talk-generator#24]
There are times when the slide Title box shows "Click here to add text". Not sure if this is an issue with the generator or with Powerpoint for Mac. 

[Example Slide](https://shaun.lol/joke/10/). Tested on Powerpoint for Mac. Do not have windows so could not confirm if it was a platform specific issue.

Will defer to @korymath @TWinters on proper handling.

**Comment by twinters** [comment]
This is usually intentional. It's the powerpoint template having a placeholder spot for a title, but the generator sometimes decides to not fill a title in that placeholder e.g. when there is a strong image already taking the focus :)
