### ISSUE TITLE
Talkgenerator.submodules can use loggers instead of print

### ISSUE THREAD

**Issue by h0h0h0** [korymath/talk-generator#27]
We can configure the talkgenerator submodules to use python `logging` module instead of printing out on standard out. This will allow consumers of the modules (those using the generators raw for other purposes) to configure the output as they see fit. 

The talkgenerator.run module would then configure the loggers to continue to print on standard out. 

Not a major thing needed for now since most people will run the talkgenerator from the command line (and thus probably want the output in standard out. This is more of a pythonic best practice that we can have the codebase follow.

**Comment by twinters** [comment]
Should be solved with this pull-request: [https://github.com/korymath/talk-generator/pull/47](https://github.com/korymath/talk-generator/pull/47)
