### ISSUE TITLE
add image filter for weird and NSFW stuff

### ISSUE THREAD

**Issue by korymath** [korymath/talk-generator#3]

**Comment by twinters** [comment]
The best way of achieving this would be adding another PresentationSchema object, next to our "default" and "test" presentation schemas, which only uses generators that we know are only capable of generating SFW content.
We could also create some new generators for this schema by adding NSFW filters to some of our existing, riskier image generators and text generators. That might require some more effort I guess.
Currently, I don't think our  generated presentations are NSFW, but the upcoming generators might indeed increase that risk.

**Comment by korymath** [comment]
Good thinking. I was also thinking that this is a good final layer of human curation. So it is not immediately necessary.
