### ISSUE TITLE
Conclusions text should be dynamic. 

### ISSUE THREAD

**Issue by korymath** [korymath/talk-generator#33]
Currently the conclusions text is always the same. 

`Conclusion 1                   Conclusion 2`

Perhaps we can use other templates to update the way that the last slide is presented?

**Comment by korymath** [comment]
This logic is all located in:
https://github.com/korymath/talk-generator/blob/e0973d994c3d42f6ccd4c3853290fa455dace3bf/talkgenerator/schema/schemas.py#L596

Likely a new `source` would be created which can build dynamic Concluding text.

Sometimes no words would be necessary.

**Comment by twinters** [comment]
Improved this: made the conclusion texts much more dynamic, able to be empty and even the title of the presentation.
