### ISSUE TITLE
Using Multiple Input Keywords

### ISSUE THREAD

**Issue by korymath** [korymath/talk-generator#38]
Imagine a situation where a user does not only want to input a single word for the topic of a presentation, but rather, they want to input a sequence of words which together serve as a set of topics for the presentation.

Rather than input: `cat` -> output: slides related to `cat` and related things, the input might be `cat, animal fight, new house, new cat` -> output: slides which follow the `story` that the user has input. 

How might we handle handling a sequence of multiple keywords?

**Comment by twinters** [comment]
Would be a cool feature indeed. Would not be hard to implement into our current system.

How do you see the slide seed distribution if  `cat, animal fight, new house, new cat` were to be entered in a 10 slide presentation? `cat` in the first slide, `new cat` on the last one and the others in between, and unfilled slides having random related words to the previous words, like our system currently does? Or should the final/conclusion slide somehow capture the whole story, or just the first topic (e.g. `cat`)?

**Comment by korymath** [comment]
Yes, I think that we could create a topic landscape, so for instance... if you have 10 slides, you would use cat on the first one 'animal fight'  on the third one, and some word halfway in-between both on the second slide. 

This also means we will need to handle multiple input words (currently topic words make up filenames and have spaces in them which could cause problems down the road)

**Comment by twinters** [comment]
Implemented and pushed to dev branch! :)
