### ISSUE TITLE
downloaded files default to a temp directory instead of current working

### ISSUE THREAD

**Issue by h0h0h0** [korymath/talk-generator#40]
I'd like to shift the downloaded file manager to download files to a temp directory that can be removed by the OS during it's normal times.   python has a facility for this called tempfiles and it's built in. Thanks python.

Thoughts?

**Comment by twinters** [comment]
Sounds great! Way cleaner than the way we currently do it! I think there is one function that already handles all of the downloading anyway, so should be a fairly easy improvement by only changing some lines there.

**Comment by h0h0h0** [comment]
Here's the way it could work.

Currently the system downloads to a download directory located in the python package directory itself. This is probably NOT a blocker piece of tech debt; but it does have a little bit of a code smell to it since we are writing and making changes to the python package directory and that directory is usually expected to stay static.

So where is a great place to keep these downloaded files around when needed but store them in a place that a user can expect to examine and even change if necessary? We are going to use a _user data directory_ that is OS specific. 

The https://pypi.org/project/appdirs/ libary has a great write up on this. To save you the trouble of going to the file:

```

the problem
What directory should your app use for storing user data? If running on Mac OS X, you should use:

> ~/Library/Application Support/<AppName>

If on Windows (at least English Win XP) that should be:

> C:\Documents and Settings\<User>\Application Data\Local Settings\<AppAuthor>\<AppName>

or possibly:

> C:\Documents and Settings\<User>\Application Data\<AppAuthor>\<AppName>
for roaming profiles but that is another story.

```

## The solution

Introduce a download manager that makes use of the `appdirs` python library and move the downloaded directory to the user data directory. 

### Change Boundaries

The change should only affect download directory that the `talkgenerator.sources` uses. Leave other directories alone for now. This will be a pilot.

**Comment by korymath** [comment]
+1, I like the proposed solution to the data download directories / cross platform. This would likely work on linux / server systems as well.

**Comment by twinters** [comment]
Yes indeed, sounds cool! Although we don't really need the files after generating the slide deck (as the PowerPoint format embeds these files). Will these downloaded files then still be removed after generation as originally planned?

**Comment by korymath** [comment]
This should be optional. 

If you want to keep the “harvest” you should be able to specify an output directory where the output pptx and a directory of ‘source’ files.
