### ISSUE TITLE
Raw text templates should be stored in a folder, and pulled into python code

### ISSUE THREAD

**Issue by korymath** [korymath/talk-generator#5]
I added the templates to a template folder. From there we can add to separate lists and then pull into a data structure which holds our templates when we start the generator. This is a way of separating code and data.

**Comment by twinters** [comment]
Yes absolutely! :) This is how I usually work as well, but I'm just slowly figuring out how to do things with Python :D I'll update it soon! :)

**Comment by korymath** [comment]
Right on, thank you! 

life_lesson_templates and synonym_templates should be the first to be fixed. 

Perhaps you can 1) load all the templates into a nested dictionary when the program launches?
