### ISSUE TITLE
Support German

### ISSUE THREAD

**Issue by faragos** [korymath/talk-generator#63]
Hey :) 

I love your website and tool. Would it be easily possible to support German? So I could use the slides with my friends.

best regards
Marco

**Comment by twinters** [comment]
Hi! Glad to hear you're enjoying the talk generator!

One of the easiest solutions would probably be to use [PowerPoint's "Translate Slides" functionality](https://www.microsoft.com/en-us/translator/business/powerpoint/#presentationtranslator).

We might build support for different languages into the tool directly at some point, but it's not high on the road map.
It would probably be easiest by just translating the generated presentation object itself.
It should in theory be possible by translating all non-urls in the `presentation` dictionary [here](https://github.com/korymath/talk-generator/blob/42d750213251acdd6d9cfd65f2d2145aeff6a845/talkgenerator/generator.py#L108), e.g. using [Google Translate](https://pypi.org/project/googletrans/).
If you're feeling up for the challenge, feel free to send a pull-request. If not, I might look into this into the future, although it won't be in the next weeks probably :)
