### ISSUE TITLE
Server Environment Variables

### ISSUE THREAD

**Issue by twinters** [korymath/talk-generator#8]
Currently, CircleCI is not able to test all the generators due to missing Reddit authentication.
This is due to the fact that I don't want these secrets exposed in the repository in case we ever make it public.
We can get around this problem by adding an alternative way of entering these three keys necessary to create the access to Reddit by having server environment variables. This will also allow us to more easily set up a server (e.g. on Heroku) with these server variables.
We should probably look into how to do this properly

**Comment by korymath** [comment]
Happy to take this one on. It will be important for deployment to a server for sure.

**Comment by h0h0h0** [comment]
I have a branch coming with [environs](https://github.com/sloria/environs). You can use this .env file to move all data/auth authorization info into the .env file as keys.  Those values will be available to modules that import our settings info. 

The circleCI environment should let us define the .env file that is used in the run.

**Comment by korymath** [comment]
This is great. Thank you.  

PR ready?

**Comment by h0h0h0** [comment]
Very soon. finishing touches.
