### ISSUE TITLE
Getting Pattern to work

### ISSUE THREAD

**Issue by twinters** [korymath/talk-generator#9]
[Pattern ](https://github.com/clips/pattern)is a very powerful Python library that would allow us to do more linguistic operations in our text generator, and thus offer more extensive possibilities in the text generator.
However, this used to be only available in Python 2, and only *very* recently started to be available in Python 3. I tried getting it to work with our code, but it didn't work out. We should probably look into this again in the near future when better support for Python 3 is provided, as they seem quite actively pushing that version out soon.

**Comment by korymath** [comment]
What would be the desired use case? As in, what does the best interface look like:

```
output = pattern_func(input) 
```

But, what do input and output look like?
Do we want to be able to parse the input better? What I am wondering is if there is another tool that will give this without colliding with our existing code as much. That is, which of the functions here do we like most: https://www.clips.uantwerpen.be/pages/pattern ... It is really nice to have these functions for understanding the language, and it is nice that they have API's already built out. 

What would a basic unit test look like that is failing with this new code?

**Comment by korymath** [comment]
@twinters is this still something we want? 

If not, I will close this issue.

If so, here are some notes on getting Pattern to work from [here](https://github.com/clips/pattern/issues/275):
`brew install mysqlclient` 
More details on how to do it on MacOS: https://ruddra.com/posts/install-mysqlclient-macos/

**Comment by twinters** [comment]
I think we don't require it that much any more, indeed.
